product=input("What did you buy?")
quantity=input("How many did you buy?")
price=input("How much did it cost?")
bill=int(quantity)*float(price)
print()
print("TESCO")
print("Today's Purchases:")
print(quantity, "x", product, "£"+price)
print("Total Cost: £"+ str(bill))
print()
print("Thank you for shopping at Tesco")
print("--------")
